### ISSUE TITLE
Modal jumps when closing

### ISSUE THREAD

**Issue by acerbastimur** [nysamnang/react-native-raw-bottom-sheet#44]
Hi, we I try to close my modal, it jumps to upper positions. How can i solve it ?

Video:

https://streamable.com/6m6gp

My code :

`<RBSheet
          ref={ref => {
            CampaignDetailsStore.campaignDetailsHalfModalRef = ref;
          }}
          duration={1000}
          closeOnDragDown
          animationType="slide"
          customStyles={{
            wrapper: {backgroundColor: 'rgba(0,0,0,0.02)'},
            container: {
              borderTopRightRadius: 40,
              borderTopLeftRadius: 40,
              paddingTop: 2,
              height: 'auto',
            },
            draggableIcon: {width: 100, height: 4, backgroundColor: Colors.SECONDARY},
          }}>
          <CampaignDetails navigation={navigation} />
        </RBSheet>`

**Comment by acerbastimur** [comment]
[https://streamable.com/6m6gp](url)

**Comment by nysamnang** [comment]
@acerbastimur Nothing wrong with this behaviour. There are two layers when you open bottom sheet, one is the bottom sheet area which shows your content and the other one is the blank area on the top of your content that you can touch to close bottom sheet.
In your snippet code, you set customStyles `wrapper: { backgroundColor: 'rgba(0,0,0,0.02)' }` it means that you set color of the blank area to `'rgba(0,0,0,0.02)'`. When you close the bottom sheet this blank area looks like jumping to the top but actually it showed since you open the bottom sheet.
So conclusion, you'll have to set backgroundColor to `wrapper: { backgroundColor: 'transparent' }` to solve this issue.

**Comment by acerbastimur** [comment]
Thanks for your reply! 

In fact, I want to add shadow to container but when I set something like that :

` <RBSheet
          ref={ref => {
            CampaignDetailsModalStore.campaignDetailsHalfModalRef = ref;
          }}
          duration={50}
          closeOnDragDown
          animationType="slide"
          customStyles={{
            wrapper: {backgroundColor: 'transparent'},
            container: {
              borderTopRightRadius: 40,
              borderTopLeftRadius: 40,
              paddingTop: 2,
              height: 'auto',
              elevation: 3,
              shadowColor: 'black',
              shadowOffset: {
                width: 0,
                height: 3,
              },
              shadowRadius: 2,
              shadowOpacity: 0.2,
            },
            draggableIcon: {width: 100, height: 4, backgroundColor: Colors.SECONDARY},
          }}>`

it doesnt show shadow. So I set background color but there is this problem :) 

Can you say why my shadow doesn't effect ?

**Comment by nysamnang** [comment]
@acerbastimur Try animationType="none" or delete this line of code (default "none").

**Comment by shamshirgreyskymedia** [comment]
@nysamnang applying animationType="none" removes the animation.
Is there any solution with the animation?
